export const LightColors = {
  primary: '#8B1A4A',
  primaryDark: '#6B1238',
  accent: '#00B5C8',
  background: '#F5F5F5',
  card: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#666666',
  textLight: '#999999',
  border: '#E5E5E5',
  success: '#27AE60',
  danger: '#E74C3C',
  warning: '#E8980E',
  white: '#FFFFFF',
  black: '#000000',
  tabBar: '#EFEFEF',
  tabBarActive: '#8B1A4A',
  tabBarInactive: '#888888',
  shadow: 'rgba(0,0,0,0.08)',
  weekStripBg: '#E8E8E8',
  weekStripBgAlt: '#D8D8D8',
  selectedDayBg: '#D4E8F5',
  selectedDayBorder: '#253960',
};

export const DarkColors: typeof LightColors = {
  primary: '#8B1A4A',
  primaryDark: '#6B1238',
  accent: '#00B5C8',
  background: '#111111',
  card: '#1E1E1E',
  text: '#F0F0F0',
  textSecondary: '#DDDDDD',
  textLight: '#FFFFFF',
  border: '#2C2C2C',
  success: '#27AE60',
  danger: '#E74C3C',
  warning: '#E8980E',
  white: '#FFFFFF',
  black: '#000000',
  tabBar: '#1A1A1A',
  tabBarActive: '#8B1A4A',
  tabBarInactive: '#FFFFFF',
  shadow: 'rgba(0,0,0,0.4)',
  weekStripBg: '#1A1A1A',
  weekStripBgAlt: '#141414',
  selectedDayBg: '#263040',
  selectedDayBorder: '#5C7A96',
};

export const Colors = LightColors;
export type ColorPalette = typeof LightColors;

export const EventColors: Record<string, string> = {
  church:    '#E05C6B',
  travel:    '#800000',
  meal:      '#D2691E',
  activity:  '#E8B820',
  work:      '#2ECC71',
  service:   '#1A3A6B',
  school:    '#2979FF',
  temple:    '#00B5C8',
  prayer:    '#A29BFE',
  scripture: '#9B59B6',
  exercise:  '#795548',
  other:     '#9E9E9E',
  task:      '#4E342E',
};

export const EventTypeLabels: Record<string, string> = {
  church:    'Church',
  travel:    'Travel',
  meal:      'Meal',
  activity:  'Activity',
  work:      'Work',
  service:   'Service',
  school:    'School',
  temple:    'Temple',
  prayer:    'Prayer',
  scripture: 'Scripture Study',
  exercise:  'Exercise',
  other:     'Other',
  task:      'Task',
};

export const EventTypeConfig: Record<string, { defaultMinutes: number; hasCheckbox: boolean }> = {
  church:    { defaultMinutes: 30, hasCheckbox: false },
  travel:    { defaultMinutes: 30, hasCheckbox: false },
  meal:      { defaultMinutes: 30, hasCheckbox: false },
  activity:  { defaultMinutes: 30, hasCheckbox: false },
  work:      { defaultMinutes: 30, hasCheckbox: false },
  service:   { defaultMinutes: 30, hasCheckbox: false },
  school:    { defaultMinutes: 30, hasCheckbox: false },
  temple:    { defaultMinutes: 30, hasCheckbox: false },
  prayer:    { defaultMinutes: 15, hasCheckbox: false },
  scripture: { defaultMinutes: 30, hasCheckbox: false },
  exercise:  { defaultMinutes: 30, hasCheckbox: false },
  other:     { defaultMinutes: 30, hasCheckbox: false },
  task:      { defaultMinutes: 15, hasCheckbox: false },
};
