export const Colors = {
  primary: '#8B1A4A',
  primaryDark: '#6B1238',
  accent: '#00B5C8',
  background: '#F5F5F5',
  card: '#FFFFFF',
  text: '#1A1A1A',
  textSecondary: '#666666',
  textLight: '#999999',
  border: '#E5E5E5',
  success: '#27AE60',
  danger: '#E74C3C',
  warning: '#F39C12',
  white: '#FFFFFF',
  black: '#000000',
  tabBar: '#FFFFFF',
  tabBarActive: '#8B1A4A',
  tabBarInactive: '#999999',
  shadow: 'rgba(0,0,0,0.08)',
};

export const EventColors: Record<string, string> = {
  prayer:    '#A29BFE',
  scripture: '#9B59B6',
  temple:    '#00B5C8',
  church:    '#E05C6B',
  service:   '#1A3A6B',
  meal:      '#D2691E',
  school:    '#2979FF',
  work:      '#2ECC71',
  exercise:  '#795548',
  travel:    '#800000',
  activity:  '#F4D03F',
  other:     '#9E9E9E',
  task:      '#4E342E',
};

export const EventTypeLabels: Record<string, string> = {
  prayer:    'Prayer',
  scripture: 'Scripture Study',
  temple:    'Temple',
  church:    'Church',
  service:   'Service',
  meal:      'Meal',
  school:    'School',
  work:      'Work',
  exercise:  'Exercise',
  travel:    'Travel',
  activity:  'Activity',
  other:     'Other',
  task:      'Task',
};

export const EventTypeConfig: Record<string, { defaultMinutes: number; hasCheckbox: boolean }> = {
  prayer:    { defaultMinutes: 15, hasCheckbox: false },
  scripture: { defaultMinutes: 30, hasCheckbox: false },
  temple:    { defaultMinutes: 30, hasCheckbox: false },
  church:    { defaultMinutes: 30, hasCheckbox: false },
  service:   { defaultMinutes: 30, hasCheckbox: false },
  meal:      { defaultMinutes: 30, hasCheckbox: false },
  school:    { defaultMinutes: 30, hasCheckbox: false },
  work:      { defaultMinutes: 30, hasCheckbox: false },
  exercise:  { defaultMinutes: 30, hasCheckbox: false },
  travel:    { defaultMinutes: 30, hasCheckbox: false },
  activity:  { defaultMinutes: 30, hasCheckbox: false },
  other:     { defaultMinutes: 30, hasCheckbox: false },
  task:      { defaultMinutes: 15, hasCheckbox: false },
};
